CREATE TABLE IF NOT EXISTS
	candidates (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		discord_id VARCHAR(32) UNIQUE NOT NULL,
		name VARCHAR(100) NOT NULL,
	);

CREATE TABLE IF NOT EXISTS
	votes (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		type TEXT NOT NULL,
		candidate INTEGER NOT NULL,
		FOREIGN KEY (candidate) REFERENCES candidates (id)
	);

CREATE TABLE IF NOT EXISTS
	ballots (voter INTEGER PRIMARY KEY);
