DROP TABLE IF EXISTS votes;
DROP TABLE IF EXISTS ballots;
DROP TABLE IF EXISTS candidates;
DROP TABLE IF EXISTS ballot_groups;
CREATE TABLE IF NOT EXISTS candidates (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	discord_id VARCHAR(32) UNIQUE NOT NULL,
	name VARCHAR(100) NOT NULL,
	ballot_group INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS ballot_groups (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(100) NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS votes (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	type TEXT NOT NULL,
	candidate VARCHAR(32) NOT NULL,
	ballot_group INTEGER NOT NULL,
	voter VARCHAR(32) NOT NULL,
	FOREIGN KEY (candidate) REFERENCES candidates (discord_id),
	FOREIGN KEY (ballot_group) REFERENCES ballot_groups (id)
);
CREATE TABLE IF NOT EXISTS ballots (
	voter VARCHAR(32) NOT NULL,
	ballot_group INTEGER NOT NULL,
	submitted_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (voter, ballot_group),
	FOREIGN KEY (ballot_group) REFERENCES ballot_groups (id)
);